[build]
publish = "portofolio statis/index.html" # Ganti dengan direktori tempat file HTML kamu.
functions = "functions" # Pastikan ini menunjuk ke folder functions.

[functions]
directory = "functions"